Fix/evandro fixes
marcelokscunha/amazon-sagemaker-workshop pull request #2
Opened 2021-07-31 21:23 UTC by evandrofranco

Adding SM Clarify on Lab 3-Evaluation (explanation) and some general fixes.

2021-08-03 19:07 UTC, marcelokscunha commented on 6-Pipelines/pipelines.ipynb
> +   "execution_count": 7,
Just "clear all outputs" for this last lab so that users don't already see all the answers.

2021-08-03 19:09 UTC, marcelokscunha requested changes
The new Clarify lab looks good, thanks for adding it!
Just one minor modification in the last Lab 6-Pipelines (clear all outputs so that users don't see all the answers beforehand) and we can approve it.

Thanks!

2021-08-03 21:29 UTC, evandrofranco commented
Done!

2021-08-04 01:14 UTC, marcelokscunha approved these changes

2021-08-04 01:14 UTC, merged